// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByba4KxJLDGXZtmkP8gB9N7r47su8sEhY',
    appId: '1:455307394569:web:ffef66a1e37adcc0d982d8',
    messagingSenderId: '455307394569',
    projectId: 'pmsn2023-b50de',
    authDomain: 'pmsn2023-b50de.firebaseapp.com',
    storageBucket: 'pmsn2023-b50de.appspot.com',
    measurementId: 'G-S6CSFKHZQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWNN1W2GplyNmumVOAlhSk0OsQ0eD3eU',
    appId: '1:455307394569:android:88a7fb8956936bd8d982d8',
    messagingSenderId: '455307394569',
    projectId: 'pmsn2023-b50de',
    storageBucket: 'pmsn2023-b50de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFilfTNRKYy8PrFc50wPHb_MhnjeWej4',
    appId: '1:455307394569:ios:6734b38f43b323d4d982d8',
    messagingSenderId: '455307394569',
    projectId: 'pmsn2023-b50de',
    storageBucket: 'pmsn2023-b50de.appspot.com',
    iosBundleId: 'com.example.finalProjectPmsn2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFilfTNRKYy8PrFc50wPHb_MhnjeWej4',
    appId: '1:455307394569:ios:16cf7f5c709dc686d982d8',
    messagingSenderId: '455307394569',
    projectId: 'pmsn2023-b50de',
    storageBucket: 'pmsn2023-b50de.appspot.com',
    iosBundleId: 'com.example.finalProjectPmsn2023.RunnerTests',
  );
}
